# Generated by Django 4.1.7 on 2023-03-01 20:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_app", "0002_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="value",
            field=models.CharField(max_length=255, unique=True, verbose_name="Токен"),
        ),
    ]
